export const SUBMIT = "SEARCH_SUBMIT";
export const ADD_STAFF = "ADD_STAFF";
// STAFFS
export const ADD_STAFFS = "ADD_STAFFS";
export const STAFFS_LOADING = "STAFFS_LOADING";
export const STAFFS_FAILED = "STAFFS_FAILED";
export const STAFFS_DEPARTMENT = "STAFFS_DEPARTMENT";
// DEPARTMENTS
export const ADD_DEPARTMENTS = "ADD_DEPARTMENTS";
export const DEPARTMENTS_LOADING = "DEPARTMENTS_LOADING";
export const DEPARTMENTS_FAILED = "DEPARTMENTS_FAILED";
// SALARY
export const ADD_SALARY = "ADD_SALARY";
export const SALARY_LOADING = "SALARY_LOADING";
export const SALARY_FAILED = "SALARY_FAILED";
